### ISSUE TITLE
Make Admin 2.0

### ISSUE THREAD

**Issue by Appleguy15** [PSCS-Coding/Attendance_System#99]

**Comment by Appleguy15** [comment]
This fill fix #93

**Comment by Appleguy15** [comment]
#96 #86 Will both tie into this.

**Comment by badtzmaru** [comment]
according to nic, the broken things are edit groups and a double header call on edit events

**Comment by badtzmaru** [comment]
also @Appleguy15 @nwarmenh this issue is exactly the example of why we don't need a "complete/pullable" label; we don't know if its pull-able until we test it and if we test it and it doesn't work, then we have to remove all the labels? we should just list the issues that will be closed in the pull request instead of juggling useless labels.

**Comment by Appleguy15** [comment]
@nwarmenh Admin 2.0 is ready to be merged. @badtzmaru The issues that you brought up above was resolved on Thursday.
